name: sitespeed.io
on: push
jobs:
  run-sitespeed:
    runs-on: ubuntu-latest
    name: running sitespeed.io
    steps:
      - name: code checkout
        uses: actions/checkout@v2
     
     # Make directory to upload the test results
      - name: Make Directory for results
        run: mkdir -p testResults
     
      - name: running sitespeed.io container with arguments and optional Docker options
        run: docker run --rm -v "$(pwd):/sitespeed.io" sitespeedio/sitespeed.io:25.7.3  --outputFolder /sitespeed.io/sitespeed-result/ https://mitesh411.github.io/MyResume/ -n 1
      
    # Upload the contents of Test Results directory to workspace
      - name: Output the run Details
        uses: actions/upload-artifact@v3
        with:
          name: RunReports
          path: /sitespeed.io/sitespeed-result/
